#DEPARTAMENTO
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1',  'Guatemala', ' ', 'departamento');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('2',  'El Progreso', ' ', 'departamento');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('3',  'Sacatepéquez', ' ', 'departamento');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('4',  'Chimaltenango', ' ', 'departamento');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('5',  'Escuintla', ' ', 'departamento');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('6',  'Santa Rosa', ' ', 'departamento');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('7',  'Sololá', ' ', 'departamento');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('8',  'Totonicapán', ' ', 'departamento');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('9',  'Quetzaltenango', ' ', 'departamento');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('10',  'Suchitepéquez', ' ', 'departamento');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('11',  'Retalhuleu', ' ', 'departamento');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('12',  'San Marcos', ' ', 'departamento');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('13',  'Huehuetenango', ' ', 'departamento');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('14',  'Quiché', ' ', 'departamento');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('15',  'Baja Verapaz', ' ', 'departamento');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('16',  'Alta Verapaz', ' ', 'departamento');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('17',  'Petén', ' ', 'departamento');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('18',  'Izabal', ' ', 'departamento');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('19',  'Zacapa', ' ', 'departamento');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('20',  'Chiquimula', ' ', 'departamento');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('21',  'Jalapa', ' ', 'departamento');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('22',  'Jutiapa', ' ', 'departamento');

#MUNICIPIO
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('101',  'Guatemala', '1', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('102',  'Santa Catarina Pinula', '1', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('103',  'San José Pinula', '1', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('104',  'San José del Golfo', '1', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('105',  'Palencia', '1', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('106',  'Chinautla', '1', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('107',  'San Pedro Ayampuc', '1', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('108',  'Mixco', '1', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('109',  'San Pedro Sacatepéquez', '1', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('110',  'San Juan Sacatepéquez', '1', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('111',  'San Raymundo', '1', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('112',  'Chuarrancho', '1', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('113',  'Fraijanes', '1', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('114',  'Amatitlán', '1', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('115',  'Villa Nueva', '1', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('116',  'Villa Canales', '1', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('117',  'Petapa', '1', 'municipio');

INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('118',  'Pavoncito', '1', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('119',  'Granja Modelo Pavon', '1', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('120',  'Centro Preventivo zona 18', '1', 'municipio');

INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('201',  'Guastatoya', '2', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('202',  'Morazán', '2', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('203',  'San Agustín Acasaguastlán', '2', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('204',  'San Cristóbal Acasaguastlán', '2', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('205',  'El Jícaro', '2', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('206',  'Sansare', '2', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('207',  'Sanarate', '2', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('208',  'San Antonio la Paz', '2', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('301',  'Antigua Guatemala', '3', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('302',  'Jocotenango', '3', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('303',  'Pastores', '3', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('304',  'Sumpango', '3', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('305',  'Santo Domingo Xenacoj', '3', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('306',  'Santiago Sacatepéquez', '3', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('307',  'San Bartolomé Milpas Altas', '3', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('308',  'San Lucas Sacatepéquez', '3', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('309',  'Santa Lucía Milpas Altas', '3', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('310',  'Magdalena Milpas Altas', '3', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('311',  'Santa María de Jesús', '3', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('312',  'Ciudad Vieja', '3', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('313',  'San Miguel Dueñas', '3', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('314',  'Alotenango', '3', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('315',  'San Antonio Aguas Calientes', '3', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('316',  'Santa Catarina Barahona', '3', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('401',  'Chimaltenango', '4', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('402',  'San José Poaquil', '4', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('403',  'San Martín Jilotepeque', '4', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('404',  'Comalapa', '4', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('405',  'Santa Apolonia', '4', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('406',  'Tecpán Guatemala', '4', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('407',  'Patzún', '4', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('408',  'Pochuta', '4', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('409',  'Patzicía', '4', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('410',  'Santa Cruz Balanyá', '4', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('411',  'Acatenango', '4', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('412',  'Yepocapa', '4', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('413',  'San Andrés Itzapa', '4', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('414',  'Parramos', '4', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('415',  'Zaragoza', '4', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('416',  'El Tejar', '4', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('501',  'Escuintla', '5', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('502',  'Santa Lucía Cotzumalguapa', '5', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('503',  'La Democracia', '5', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('504',  'Siquinalá', '5', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('505',  'Masagua', '5', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('506',  'Tiquisate', '5', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('507',  'La Gomera', '5', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('508',  'Guanagazapa', '5', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('509',  'San José', '5', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('510',  'Iztapa', '5', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('511',  'Palín', '5', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('512',  'San Vicente Pacaya', '5', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('513',  'Nueva Concepción', '5', 'municipio');

INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('514',  'Granja Modelo Canada', '5', 'municipio');

INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('601',  'Cuilapa', '6', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('602',  'Barberena', '6', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('603',  'Santa Rosa de Lima', '6', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('604',  'Casillas', '6', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('605',  'San Rafael las Flores', '6', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('606',  'Oratorio', '6', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('607',  'San Juan Tecuaco', '6', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('608',  'Chiquimulilla', '6', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('609',  'Taxisco', '6', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('610',  'Santa María Ixhuatán', '6', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('611',  'Guazacapán', '6', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('612',  'Santa Cruz Naranjo', '6', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('613',  'Pueblo Nuevo Viñas', '6', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('614',  'Nueva Santa Rosa', '6', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('701',  'Sololá', '7', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('702',  'San José Chacayá', '7', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('703',  'Santa María Visitación', '7', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('704',  'Santa Lucía Utatlán', '7', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('705',  'Nahualá', '7', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('706',  'Santa Catarina Ixtahuacán', '7', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('707',  'Santa Clara la Laguna', '7', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('708',  'Concepción', '7', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('709',  'San Andrés Semetabaj', '7', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('710',  'Panajachel', '7', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('711',  'Santa Catarina Palopó', '7', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('712',  'San Antonio Palopó', '7', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('713',  'San Lucas Tolimán', '7', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('714',  'Santa Cruz la Laguna', '7', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('715',  'San Pablo la Laguna', '7', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('716',  'San Marcos la Laguna', '7', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('717',  'San Juan la Laguna', '7', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('718',  'San Pedro la Laguna', '7', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('719',  'Santiago Atitlán', '7', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('801',  'Totonicapán', '8', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('802',  'San Cristóbal Totonicapán', '8', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('803',  'San Francisco el Alto', '8', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('804',  'San Andrés Xecul', '8', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('805',  'Momostenango', '8', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('806',  'Santa María Chiquimula', '8', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('807',  'Santa Lucía la Reforma', '8', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('808',  'San Bartolo', '8', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('901',  'Quetzaltenango', '9', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('902',  'Salcajá', '9', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('903',  'Olintepeque', '9', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('904',  'San Carlos Sija', '9', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('905',  'Sibilia', '9', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('906',  'Cabricán', '9', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('907',  'Cajolá', '9', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('908',  'San Miguel Siguilá', '9', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('909',  'Ostuncalco', '9', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('910',  'San Mateo', '9', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('911',  'Concepción Chiquirichapa', '9', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('912',  'San Martín Sacatepéquez', '9', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('913',  'Almolonga', '9', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('914',  'Cantel', '9', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('915',  'Huitán', '9', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('916',  'Zunil', '9', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('917',  'Colomba', '9', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('918',  'San Francisco la Unión', '9', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('919',  'El Palmar', '9', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('920',  'Coatepeque', '9', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('921',  'Génova', '9', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('922',  'Flores Costa Cuca', '9', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('923',  'La Esperanza', '9', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('924',  'Palestina de los Altos', '9', 'municipio');

INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('925',  'Granja Modelo Cantel', '9', 'municipio');

INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1001',  'Mazatenango', '10', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1002',  'Cuyotenango', '10', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1003',  'San Francisco Zapotitlán', '10', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1004',  'San Bernardino', '10', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1005',  'San José el Idolo', '10', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1006',  'Santo Domingo Suchitepéquez', '10', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1007',  'San Lorenzo', '10', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1008',  'Samayac', '10', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1009',  'San Pablo Jocopilas', '10', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1010',  'San Antonio Suchitepéquez', '10', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1011',  'San Miguel Panán', '10', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1012',  'San Gabriel', '10', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1013',  'Chicacao', '10', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1014',  'Patulul', '10', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1015',  'Santa Bárbara', '10', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1016',  'San Juan Bautista', '10', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1017',  'Santo Tomás la Unión', '10', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1018',  'Zunilito', '10', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1019',  'Pueblo Nuevo', '10', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1020',  'Río Bravo', '10', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1021',  'San José La Máquina', '10', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1101',  'Retalhuleu', '11', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1102',  'San Sebastián', '11', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1103',  'Santa Cruz Muluá', '11', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1104',  'San Martín Zapotitlán', '11', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1105',  'San Felipe', '11', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1106',  'San Andrés Villa Seca', '11', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1107',  'Champerico', '11', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1108',  'Nuevo San Carlos', '11', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1109',  'El Asintal', '11', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1201',  'San Marcos', '12', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1202',  'San Pedro Sacatepéquez', '12', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1203',  'San Antonio Sacatepéquez', '12', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1204',  'Comitancillo', '12', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1205',  'San Miguel Ixtahuacán', '12', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1206',  'Concepción Tutuapa', '12', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1207',  'Tacaná', '12', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1208',  'Sibinal', '12', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1209',  'Tajumulco', '12', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1210',  'Tejutla', '12', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1211',  'San Rafael Pié de la Cuesta', '12', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1212',  'Nuevo Progreso', '12', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1213',  'El Tumbador', '12', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1214',  'El Rodeo', '12', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1215',  'Malacatán', '12', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1216',  'Catarina', '12', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1217',  'Ayutla', '12', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1218',  'Ocós', '12', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1219',  'San Pablo', '12', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1220',  'El Quetzal', '12', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1221',  'La Reforma', '12', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1222',  'Pajapita', '12', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1223',  'Ixchiguán', '12', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1224',  'San José Ojetenán', '12', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1225',  'San Cristóbal Cucho', '12', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1226',  'Sipacapa', '12', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1227',  'Esquipulas Palo Gordo', '12', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1228',  'Río Blanco', '12', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1229',  'San Lorenzo', '12', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1230',  'La Blanca', '12', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1301',  'Huehuetenango', '13', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1302',  'Chiantla', '13', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1303',  'Malacatancito', '13', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1304',  'Cuilco', '13', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1305',  'Nentón', '13', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1306',  'San Pedro Necta', '13', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1307',  'Jacaltenango', '13', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1308',  'Soloma', '13', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1309',  'Ixtahuacán', '13', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1310',  'Santa Bárbara', '13', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1311',  'La Libertad', '13', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1312',  'La Democracia', '13', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1313',  'San Miguel Acatán', '13', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1314',  'San Rafael la Independencia', '13', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1315',  'Todos Santos Cuchumatán', '13', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1316',  'San Juan Atitán', '13', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1317',  'Santa Eulalia', '13', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1318',  'San Mateo Ixtatán', '13', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1319',  'Colotenango', '13', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1320',  'San Sebastián Huehuetenango', '13', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1321',  'Tectitán', '13', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1322',  'Concepción Huista', '13', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1323',  'San Juan Ixcoy', '13', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1324',  'San Antonio Huista', '13', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1325',  'San Sebastián Coatán', '13', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1326',  'Barillas', '13', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1327',  'Aguacatán', '13', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1328',  'San Rafael Petzal', '13', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1329',  'San Gaspar Ixchil', '13', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1330',  'Santiago Chimaltenango', '13', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1331',  'Santa Ana Huista', '13', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1332',  'Unión Cantinil', '13', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1401',  'Santa Cruz del Quiché', '14', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1402',  'Chiché', '14', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1403',  'Chinique', '14', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1404',  'Zacualpa', '14', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1405',  'Chajul', '14', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1406',  'Chichicastenango', '14', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1407',  'Patzité', '14', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1408',  'San Antonio Ilotenango', '14', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1409',  'San Pedro Jocopilas', '14', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1410',  'Cunén', '14', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1411',  'San Juan Cotzal', '14', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1412',  'Joyabaj', '14', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1413',  'Nebaj', '14', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1414',  'San Andrés Sajcabajá', '14', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1415',  'Uspantán', '14', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1416',  'Sacapulas', '14', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1417',  'San Bartolomé Jocotenango', '14', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1418',  'Canillá', '14', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1419',  'Chicamán', '14', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1420',  'Ixcán', '14', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1421',  'Pachalum', '14', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1501',  'Salamá', '15', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1502',  'San Miguel Chicaj', '15', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1503',  'Rabinal', '15', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1504',  'Cubulco', '15', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1505',  'Granados', '15', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1506',  'El Chol', '15', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1507',  'San Jerónimo', '15', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1508',  'Purulhá', '15', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1601',  'Cobán', '16', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1602',  'Santa Cruz Verapaz', '16', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1603',  'San Cristóbal Verapaz', '16', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1604',  'Tactic', '16', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1605',  'Tamahú', '16', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1606',  'Tucurú', '16', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1607',  'Panzós', '16', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1608',  'Senahú', '16', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1609',  'San Pedro Carchá', '16', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1610',  'San Juan Chamelco', '16', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1611',  'Lanquín', '16', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1612',  'Cahabón', '16', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1613',  'Chisec', '16', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1614',  'Chahal', '16', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1615',  'Fray Bartolomé de las Casas', '16', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1616',  'Santa Catalina la Tinta', '16', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1617',  'Raxruhá', '16', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1701',  'Flores', '17', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1702',  'San José', '17', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1703',  'San Benito', '17', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1704',  'San Andrés', '17', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1705',  'La Libertad', '17', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1706',  'San Francisco', '17', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1707',  'Santa Ana', '17', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1708',  'Dolores', '17', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1709',  'San Luis', '17', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1710',  'Sayaxché', '17', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1711',  'Melchor de Mencos', '17', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1712',  'Poptún', '17', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1713',  'Las Cruces', '17', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1714',  'El Chal', '17', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1801',  'Puerto Barrios', '18', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1802',  'Livingston', '18', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1803',  'El Estor', '18', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1804',  'Morales', '18', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1805',  'Los Amates', '18', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1901',  'Zacapa', '19', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1902',  'Estanzuela', '19', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1903',  'Río Hondo', '19', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1904',  'Gualán', '19', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1905',  'Teculután', '19', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1906',  'Usumatlán', '19', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1907',  'Cabañas', '19', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1908',  'San Diego', '19', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1909',  'La Unión', '19', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1910',  'Huité', '19', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('1911',  'San Jorge', '19', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('2001',  'Chiquimula', '20', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('2002',  'San José La Arada', '20', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('2003',  'San Juan Ermita', '20', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('2004',  'Jocotán', '20', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('2005',  'Camotán', '20', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('2006',  'Olopa', '20', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('2007',  'Esquipulas', '20', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('2008',  'Concepción Las Minas', '20', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('2009',  'Quetzaltepeque', '20', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('2010',  'San Jacinto', '20', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('2011',  'Ipala', '20', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('2101',  'Jalapa', '21', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('2102',  'San Pedro Pinula', '21', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('2103',  'San Luis Jilotepeque', '21', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('2104',  'San Manuel Chaparrón', '21', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('2105',  'San Carlos Alzatate', '21', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('2106',  'Monjas', '21', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('2107',  'Mataquescuintla', '21', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('2201',  'Jutiapa', '22', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('2202',  'El Progreso', '22', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('2203',  'Santa Catarina Mita', '22', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('2204',  'Agua Blanca', '22', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('2205',  'Asunción Mita', '22', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('2206',  'Yupiltepeque', '22', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('2207',  'Atescatempa', '22', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('2208',  'Jerez', '22', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('2209',  'El Adelanto', '22', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('2210',  'Zapotitlán', '22', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('2211',  'Comapa', '22', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('2212',  'Jalpatagua', '22', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('2213',  'Conguaco', '22', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('2214',  'Moyuta', '22', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('2215',  'Pasaco', '22', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('2216',  'San José Acatempa', '22', 'municipio');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('2217',  'Quesada', '22', 'municipio');

#ROLES
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('R001',  'Administrador', ' ', 'rol');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('R002',  'Especilista Programatica', ' ', 'rol');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('R003',  'Enlace Programatica RP', ' ', 'rol');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('R004',  'Monitoreo y Evaluacion de RP', ' ', 'rol');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('R005',  'Coordinador de Monitoreo y Evaluacion de SR', ' ', 'rol');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('R006',  'Supervisor', ' ', 'rol');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('R007',  'Promotor', ' ', 'rol');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('R008',  'Financiero', ' ', 'rol');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('R009',  'Coordinador de proyectos', ' ', 'rol');
#PERIODO 1
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('MP11', 'Enero', 1, 'mes');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('MP12', 'Febrero', 1, 'mes');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('MP13', 'Marzo', 1, 'mes');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('MP14', 'Abril', 1, 'mes');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('MP15', 'Mayo', 1, 'mes');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('MP16', 'Junio', 1, 'mes');
#PERIODO 2
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('MP21', 'Julio', 2, 'mes');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('MP22', 'Agosto', 2, 'mes');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('MP23', 'Septiembre', 2, 'mes');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('MP24', 'Octubre', 2, 'mes');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('MP25', 'Noviembre', 2, 'mes');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('MP26', 'Diciembre', 2, 'mes');
#PERIODO 3
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('MP31', 'Enero', 3, 'mes');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('MP32', 'Febrero', 3, 'mes');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('MP33', 'Marzo', 3, 'mes');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('MP34', 'Abril', 3, 'mes');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('MP35', 'Mayo', 3, 'mes');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('MP36', 'Junio', 3, 'mes');
#PERIODO 4
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('MP41', 'Julio', 4, 'mes');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('MP42', 'Agosto', 4, 'mes');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('MP43', 'Septiembre', 4, 'mes');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('MP44', 'Octubre', 4, 'mes');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('MP45', 'Noviembre', 4, 'mes');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('MP46', 'Diciembre', 4, 'mes');
#PERIODO 5
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('MP51', 'Enero', 5, 'mes');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('MP52', 'Febrero', 5, 'mes');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('MP53', 'Marzo', 5, 'mes');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('MP54', 'Abril', 5, 'mes');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('MP55', 'Mayo', 5, 'mes');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('MP56', 'Junio', 5, 'mes');
#PERIODO 6
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('MP61', 'Julio', 6, 'mes');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('MP62', 'Agosto', 6, 'mes');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('MP63', 'Septiembre', 6, 'mes');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('MP64', 'Octubre', 6, 'mes');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('MP65', 'Noviembre', 6, 'mes');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('MP66', 'Diciembre', 6, 'mes');
#ESTADOS 

INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('ES01', 'Pendiente de enviar al RP', '', 'estado');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('ES02', 'Enviado al RP', 'Enviado para revision', 'estado');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('ES03', 'Revisado por el RP', 'POA o POM revisado por el enlace', 'estado');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('ES04', 'Aprobado por el RP', 'POA o POM aprobado por el especialista', 'estado');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('ES05', 'Correccion', 'Modificar POA o POM', 'estado');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('ES06', 'Rechazado', 'POA o POM rechazado', 'estado');

INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('RE01', 'Recalendarizado', 'Cambio de fecha del POM', 'estado');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('RE02', 'Autorizado', 'Cambio Autorizado', 'estado');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('RE03', 'Rechazado', 'Cambio rechazado', 'estado');

#ESTADO DEL PROMOTOR
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('PR01', 'POM creado', 'POM creado por el promotor', 'estado');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('PR02', 'Enviado al supervisor para revision ', 'Enviado para revision', 'estado');
INSERT INTO poam.catalogo (codigo,nombre,descripcion,categoria) VALUES ('PR03', 'Correccion del POM', 'Corregir POM', 'estado');



CALL agregarUsuario("INCAP01","Faustino","", "Lopez", "Ramos", "57619399", "flopez@incap.int", "R001", 1);
CALL agregarUsuario("INCAP02","Osberto","", "Juarez", "Vasquez", "57619344", "ojuarez@incap.int", "R001", 1);